# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0b58e15178ac9f5a6ebacd717426c5c4"
name = "Tulipy-order"
handle = "tulipy-order"
application_url = "https://tulipy.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tulipy-delivery.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_customers,read_orders"

[auth]
redirect_urls = [
  "https://tulipy.onrender.com/auth/callback",
  "https://tulipy.onrender.com/auth/shopify/callback",
  "https://tulipy.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
